### ISSUE TITLE
Create Release/Tag

### ISSUE THREAD

**Issue by ConorNevin** [InVisionApp/rye#16]
Would it be possible to create a tag so that Rye plays nicely with vendoring tools like glide (preferably using SemVer 2.0)?

Thanks!

**Comment by caledhwa** [comment]
@ConorNevin - hey! We'll look into this...

**Comment by caledhwa** [comment]
Hey @ConorNevin -> Sorry this took so long, I had no idea what releasing was about. I released a v1.0.0 version that should fulfill your needs to use with GLIDE. https://github.com/InVisionApp/rye/releases
