### ISSUE TITLE
.Use duplicates its middleware each time a route is called

### ISSUE THREAD

**Issue by joshmatz** [InVisionApp/rye#20]
When .Use is specified with middleware, the middleware ends up being invoked X times for X amount of request to a particular route.

Example:

/healthcheck receives first request: .Use specified middleware runs 1 time.
/healthcheck receives second request: .Use specified middleware runs 2 times.
/healthcheck receives n request: .Use specified middleware runs n times.

**Comment by caledhwa** [comment]
Ugh, makes sense. I'll write a test around this and fix it.

**Comment by caledhwa** [comment]
Fixed by #21
