### ISSUE TITLE
should logrus be vendored revisioned?

### ISSUE THREAD

**Issue by bettse** [InVisionApp/rye#25]
I'm new to golang, but with the references to logrus, won't this pull in the bleeding edge version of logrus?

**Comment by bettse** [comment]
@talpert / @johannesinvision y'all ever see this issue?

**Comment by johannesinvision** [comment]
I had an issue with this when I had a recent version of logrus and were using rye. I'm pretty new to golang, but my intuition would be that libraries didn't vendor libraries much and left that to the final user. Of course that would lead to issues like I was experiencing, but it will reduce conflicting versions and bloat once it actually compiles.

**Comment by johannesinvision** [comment]
For what it's worth, my understanding is that rye won't pull the latest version of logrus—it will use what's in the importing repo's vendor folder (if there is one).

**Comment by dselans** [comment]
It's too late to change now but `rye` having direct refs to external libs in the main pkg is not great. While there's a _good_ chance that folks already have logrus in their project, this will _indeed_ pull logrus in when they vendor all external deps. Better solution would be that middlewares were in their own pkg.

That might have to be v2 though.

Closing.
